{
    "status": "failed", 
    "name": "test_again_mixed_nested_steps[True-False-False]", 
    "parameters": [
        {
            "name": "first_fail_before_second", 
            "value": "True"
        }, 
        {
            "name": "first_fail_after_second", 
            "value": "False"
        }, 
        {
            "name": "second_fail", 
            "value": "False"
        }
    ], 
    "parentIds": [], 
    "labels": [
        {
            "name": "testClass", 
            "value": "test.steps.nested_steps_test"
        }
    ], 
    "stop": 1482258280717, 
    "statusDetails": {
        "message": "AssertionError: assert not True", 
        "trace": "first_fail_before_second = True, first_fail_after_second = False, second_fail = False\n\n    @pytest.mark.parametrize(\"first_fail_before_second, first_fail_after_second, second_fail\", fruit_machine)\n    def test_again_mixed_nested_steps(first_fail_before_second, first_fail_after_second, second_fail):\n        with pytest.allure.step('First step'):\n>           assert not first_fail_before_second\nE           assert not True\n\ntest/steps/nested_steps_test.py:104: AssertionError"
    }, 
    "start": 1482258280716, 
    "steps": [
        {
            "name": "First step", 
            "description": null, 
            "descriptionHtml": null, 
            "steps": null, 
            "attachments": null, 
            "start": 1482258280716, 
            "stop": 1482258280716, 
            "id": null, 
            "status": "failed", 
            "statusDetails": null, 
            "parameters": null
        }
    ], 
    "fullName": "test.steps.nested_steps_test#test_again_mixed_nested_steps[True-False-False]", 
    "afters": [], 
    "id": "2cde3348bae64452798062390c1f7c9b", 
    "befores": []
}