<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1412949538851" stop="1412949560013" version="1.4.4-SNAPSHOT">
    <name>my.company.NonAsciiTest</name>
    <test-cases>
        <test-case start="1412949540562" stop="1412949540660" status="broken">
            <name>test_raise_cyrilling</name>
            <title>test_raise_cyrilling (невероятный тест кодировки!)</title>
            <description type="text">Этот тест выкидывает исключение с русскими буквами</description>
            <failure>
                <message>Exception: Невероятная проблема!</message>
                <stack-trace>java.lang.Exception: Невероятная проблема!
	at my.company.NonAsciiTest.test_raise_cyrilling(NonAsciiTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-8"/>
            </labels>
        </test-case>
        <test-case start="1412949540562" stop="1412949540565" status="passed">
            <name>test_pass</name>
            <description type="text">Этот тест проходит</description>
            <steps/>
            <attachments/>
            <labels>
                <label name="host" value="my.cool.host.com"/>
                <label name="thread" value="pool-1-thread-9"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="JUnit"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
